### ISSUE TITLE
Wrap CLI

### ISSUE THREAD

**Issue by Nanguage** [Nanguage/oneFace#4]
Wrap a CLI program to a GUI/Web interface app.

Using a .yaml as config to specify the arguments:
```
# open_browser_oneface.yaml
name: open_browser

command: python -m webbrowser {is_tab} {url} 

arguments:

  is_tab:
    type: bool
    true_content: "-t"
    false_content: ""

  url:
    type: str
```

Launch the app with:

```
$ python -m onface.wrap_cli run open_browser_oneface.yaml qt_gui
```

It will get a GUI app.
